site_name: ChemWiki  
site_url: https://wiki.rapon.wang/
copyright: 'Copyright &copy; 2019 王若鹏 All rights reserved.'  

nav:
    - Home: index.md  
    - 催化裂化:  
        - '工艺简述': FCC\proc.md    
        - '控制设施': FCC\procctrl.md   
        - '催化裂化原料表征': FCC\feedcharacter.md
        - '催化裂化催化剂': FCC\FCCcat.md
        - '装置的监控': FCC\monitor&ctrl.md
        - '产品与效益分析': FCC\products&eco.md
        - '项目执行与项目管理': FCC\pm.md
    - 甲醇制烯烃（MTO）:    
        - '烯烃生产技术概述': MTO\olefins.md
        - 'MTO技术的研究与发展': MTO\R&D.md
    - 换热器:  
        - '总述': HE/HE.md   
        - 管壳式换热器:  
            - '管壳式换热器/Shell & Tube Exchanger': HE/snt.md  
            - '管壳式换热器计算方法': HE/sntcal.md  
            - '壳程流路分析计算法': HE\流路分析.md  
        - 冷凝器: 
            - '冷凝机理分析及设计考虑因素': HE\cdsmech&design.md  
            - '冷凝器热负荷': HE\cdsheatduty.md    
            - '水平管内冷凝传热和压力降': HE\cdspresdrop.md
        - '重沸器（再沸器）/Reboiler': HE/reboiler.md   
    - 泵:
        - '总述': Pump\intro.md 
        - '离心泵': Pump\Centpump.md
    - Markdown:  
        - 'Symbols/各类符号': MD/syb.md  
        - 'LaTeX': MD/latex.md  
        - 'Grammar': MD\grammar.md
        - 'TEST': MD\TEST.md
    - 杂项: 
        - 'Negotiation': Other\MOOC_Negotiation.md   


theme:
    name: 'material'

#include_search_page: true
#search_index_only: false
plugins:
    - search
#    - git-revision-date
extra_javascript:
#    - 'javascripts\flu.js'
#    - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
#    - 'javascripts\mathjax.js'
#    - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
#    - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js'
   - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - toc:
        permalink: "&para;"
    - markdown.extensions.admonition
    - pymdownx.arithmatex
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark:
        smart_mark: false
    - pymdownx.tilde
#    - mdx_math
    - markdown_include.include:
        base_path: docs

repo_url: https://github.com/rapon233/ChemWiKi
repo_name: ChemWiKi
site_dir: build  
