site_name: ChemWiki  
copyright: '&copy; 2019 王若鹏 All rights reserved.'  

nav:
    - Home: index.md  
    - 催化裂化:  
        - 'FCC工艺简介': FCC\proc.md    
        - '控制设施': FCC\procctrl.md   
        - '催化裂化原料表征': FCC\feedcharacter.md
        - '催化裂化催化剂': FCC\FCCcat.md
    - 换热器:  
        - '总述': HE/换热器总述.md 
        - '管壳式换热器/Shell & Tube Exchanger': HE/snt.md  
        - '管壳式换热器计算方法': HE/sntcal.md  
        - '重沸器（再沸器）/Reboiler': HE/reboiler.md   
    - Markdown:  
        - 'Symbols/各类符号': MD/syb.md  
        - 'LaTeX': MD/latex.md  

theme:
  name: 'material'
#include_search_page: true
#search_index_only: false
plugins:
    - search
    - git-revision-date
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.arithmatex
    - pymdownx.details
    - pymdownx.superfences
    - mdx_math
    - markdown_include.include:
        base_path: docs

repo_url: https://github.com/rapon233/ChemWiKi
repo_name: ChemWiKi
site_dir: build  
